name: build and test 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: setup node.js environmnet
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install jest --save
      - run: npm run test